CREATE TABLE IF NOT EXISTS users(
    id TEXT PRIMARY KEY, 
    rolls INT
);

CREATE TABLE IF NOT EXISTS deathrolls(
    name TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS standardrolls(
    name TEXT PRIMARY KEY
);

